models:
  - name: stg__fhv_bases
    description: ""
    columns:
      - name: base_number
        description: ""
        tests:
          - not_null
          - unique
          - dbt_expectations.expect_column_to_exist
          - relationships:
              to: ref('fhv_bases')
              field: dispatching_base_num

      - name: base_name
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist
      
      - name: dba
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist

      - name: dba_category
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist
          - accepted_values:
              values: ["other", "uber", "lyft", "via", "juno"]

      - name: filename
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist

  - name: stg__bike_data
    description: ""
    columns:
      - name: started_at_ts
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp

      - name: ended_at_ts
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp

      - name: tripduration
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              strictly: false

      - name: start_station_id
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist

      - name: start_station_name
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist

      - name: start_lat
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: double


      - name: start_lng
        description: ""
        tests:
          - not_null
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: double

      - name: end_station_id
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist

      - name: end_station_name
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist

      - name: end_lat
        description: ""
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: double
          - dbt_expectations.expect_column_to_exist

      - name: end_lng
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: double

      - name: filename
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist
        
  - name: stg__fhv_tripdata
    description: ""
    columns:
      - name: dispatching_base_num
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist

      - name: pickup_datetime
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp

      - name: dropoff_datetime
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp

      - name: pulocationid
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: double

      - name: dolocationid
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: double

      - name: affiliated_base_number
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist

      - name: filename
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist

  - name: stg__fhvhv_tripdata
    description: ""
    columns:
      - name: hvfhs_license_num
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist

      - name: dispatching_base_num
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist

      - name: originating_base_num
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist

      - name: request_datetime
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp

      - name: on_scene_datetime
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp

      - name: pickup_datetime
        description: ""
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp

      - name: dropoff_datetime
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: timestamp

      - name: pulocationid
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint

      - name: dolocationid
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint

      - name: trip_miles
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: double

      - name: trip_time
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: bigint

      - name: base_passenger_fare
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: double

      - name: tolls
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: double

      - name: bcf
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: double

      - name: sales_tax
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: double

      - name: congestion_surcharge
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: double

      - name: airport_fee
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: double

      - name: tips
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: double

      - name: driver_pay
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: double

      - name: shared_request_flag
        description: ""
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: boolean
          - not_null

      - name: shared_match_flag
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: boolean
          - not_null

      - name: access_a_ride_flag
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: boolean

      - name: wav_request_flag
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: boolean
          - not_null

      - name: wav_match_flag
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: boolean
          - not_null

      - name: filename
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist

  - name: stg__central_park_weather  
    description: ""
    columns:
      - name: station
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist

      - name: name
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist

      - name: date
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: date

      - name: awnd
        description: ""
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: double
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0 

      - name: prcp
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: double
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0 

      - name: snow
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: double
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0 

      - name: snwd
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: double
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0 

      - name: tmax
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: integer
          - dbt_expectations.expect_column_values_to_be_between:
              max_value: 105 

      - name: tmin
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: integer

      - name: filename
        description: ""
        tests:
          - dbt_expectations.expect_column_to_exist

