sources:
  - name: main
    tables:
      - name: bike_data
        columns:
          - name: tripduration
            data_type: CHARACTER VARYING(256)
            description: "Trip duration in seconds"
          - name: starttime
            data_type: CHARACTER VARYING(256)
            description: "Trip start time"
          - name: stoptime
            data_type: CHARACTER VARYING(256)
            description: "Trip end time"
          - name: start station id
            data_type: CHARACTER VARYING(256)
            description: "Statrt station ID"
          - name: start station name
            data_type: CHARACTER VARYING(256)
            description: "Start station time"
          - name: start station latitude
            data_type: CHARACTER VARYING(256)
            description: "Start station latitude"
          - name: start station longitude
            data_type: CHARACTER VARYING(256)
            description: "Start station longitude"
          - name: end station id
            data_type: CHARACTER VARYING(256)
            description: "End station ID"
          - name: end station name
            data_type: CHARACTER VARYING(256)
            description: "End station name"
          - name: end station latitude
            data_type: CHARACTER VARYING(256)
            description: "End station latitude"
          - name: end station longitude
            data_type: CHARACTER VARYING(256)
            description: "End station longitude"
          - name: bikeid
            data_type: CHARACTER VARYING(256)
            description: " Bike ID"
          - name: usertype
            data_type: CHARACTER VARYING(256)
            description: "User type"
            tests:
              - dbt_expectations.expect_column_distinct_values_to_be_in_set:
                  value_set: ['Customer','Subscriber']
                  row_condition: "usertype is not null"
          - name: birth year
            data_type: CHARACTER VARYING(256)
            description: "User birth year"
          - name: gender
            data_type: CHARACTER VARYING(256)
            description: "User gender"
            tests: 
              - dbt_expectations.expect_column_distinct_values_to_be_in_set:
                  value_set: ['0','1','2']
                  row_condition: "gender is not null"
                  config:
                    severity: warn
          - name: ride_id
            data_type: CHARACTER VARYING(256)
            description: "Ride ID"
          - name: rideable_type
            data_type: CHARACTER VARYING(256)
            description: "Rideable Type"
          - name: started_at
            data_type: CHARACTER VARYING(256)
            description: "Start station"
          - name: ended_at
            data_type: CHARACTER VARYING(256)
            description: "End station"
          - name: start_station_name
            data_type: CHARACTER VARYING(256)
            description: "Start station name"
          - name: start_station_id
            data_type: CHARACTER VARYING(256)
            description: "Start station ID"
          - name: end_station_name
            data_type: CHARACTER VARYING(256)
            description: "End station name"
          - name: end_station_id
            data_type: CHARACTER VARYING(256)
            description: "End station ID"
          - name: start_lat
            data_type: CHARACTER VARYING(256)
            description: "Start station latitude"
          - name: start_lng
            data_type: CHARACTER VARYING(256)
            description: "Start station longitude"
          - name: end_lat
            data_type: CHARACTER VARYING(256)
            description: "End station latitude"
          - name: end_lng
            data_type: CHARACTER VARYING(256)
            description: "End station longitude"
          - name: member_casual
            data_type: CHARACTER VARYING(256)
            description: "Is a member or casual rider"
          - name: filename
            data_type: CHARACTER VARYING(256)

      - name: central_park_weather
        columns:
          - name: station
            data_type: CHARACTER VARYING(256)
            description: "Observation station"
          - name: name
            data_type: CHARACTER VARYING(256)
            description: "Station name"
          - name: date
            data_type: CHARACTER VARYING(256)
            description: "Record generated on"
          - name: awnd
            data_type: CHARACTER VARYING(256)
            description: "Average Wind Speed"
          - name: prcp
            data_type: CHARACTER VARYING(256)
            description: "Precipitation"
          - name: snow
            data_type: CHARACTER VARYING(256)
            description: "Snowfall"
          - name: snwd
            data_type: CHARACTER VARYING(256)
            description: "	Snow depth"
          - name: tmax
            data_type: CHARACTER VARYING(256)
            description: "Maximum temperature"
          - name: tmin
            data_type: CHARACTER VARYING(256)
            description: "Minimum temperature"
          - name: filename
            data_type: CHARACTER VARYING(256)

      - name: daily_citi_bike_trip_counts_and_weather
        columns:
          - name: date
            data_type: CHARACTER VARYING(256)
          - name: trips
            data_type: CHARACTER VARYING(256)
          - name: precipitation
            data_type: CHARACTER VARYING(256)
          - name: snow_depth
            data_type: CHARACTER VARYING(256)
          - name: snowfall
            data_type: CHARACTER VARYING(256)
          - name: max_temperature
            data_type: CHARACTER VARYING(256)
          - name: min_temperature
            data_type: CHARACTER VARYING(256)
          - name: average_wind_speed
            data_type: CHARACTER VARYING(256)
          - name: dow
            data_type: CHARACTER VARYING(256)
          - name: year
            data_type: CHARACTER VARYING(256)
          - name: month
            data_type: CHARACTER VARYING(256)
          - name: holiday
            data_type: CHARACTER VARYING(256)
          - name: stations_in_service
            data_type: CHARACTER VARYING(256)
          - name: weekday
            data_type: CHARACTER VARYING(256)
          - name: weekday_non_holiday
            data_type: CHARACTER VARYING(256)
          - name: filename
            data_type: CHARACTER VARYING(256)

      - name: fhv_bases
        columns:
          - name: base_number
            data_type: CHARACTER VARYING(256)
            description: "The TLC license number of the dispatching base"
            tests:
              - unique
              - not_null
          - name: base_name
            data_type: CHARACTER VARYING(256)
            description: "The official name of the base entity"
          - name: dba
            data_type: CHARACTER VARYING(256)
            description: "The “doing business as” name of the base"
          - name: dba_category
            data_type: CHARACTER VARYING(256)
            description: "The category for “doing business as”"
            tests:
              - accepted_values:
                  values: ['other', 'uber', 'lyft', 'via', 'juno']
                  config:
                    severity: warn
          - name: filename
            data_type: CHARACTER VARYING(256)

      - name: fhv_tripdata
        columns:
          - name: dispatching_base_num
            data_type: CHARACTER VARYING(256)
            description: "The TLC Base License Number of the base that dispatched the trip"
            tests: 
              - not_null
              - dbt_expectations.expect_column_to_exist
              - relationships:
                  to: source('main','fhv_bases')
                  field: base_number
                  config: 
                    severity: warn
          - name: pickup_datetime
            data_type: TIMESTAMP
            description: "The date and time of the trip pick-up"
          - name: dropoff_datetime
            data_type: TIMESTAMP
            description: "The date and time of the trip dropoff"
          - name: pulocationid
            data_type: DOUBLE
            descrription: "TLC Taxi Zone in which the trip began"
          - name: dolocationid
            data_type: DOUBLE
            description: "TLC Taxi Zone in which the trip ended"
          - name: sr_flag
            data_type: INTEGER
            description: "Indicates if the trip was a part of a shared ride chain offered by a
                          High Volume FHV company (e.g. Uber Pool, Lyft Line). For shared
                          trips, the value is 1. For non-shared rides, this field is null.
                          NOTE: For most High Volume FHV companies, only shared rides that
                          were requested AND matched to another shared-ride request over
                          the course of the journey are flagged. However, Lyft (base license
                          numbers B02510 + B02844) also flags rides for which a shared ride
                          was requested but another passenger was not successfully matched
                          to share the trip—therefore, trips records with SR_Flag=1 from those
                          two bases could indicate EITHER a first trip in a shared trip chain OR
                          a trip for which a shared ride was requested but never matched.
                          Users should anticipate an overcount of successfully shared trips
                          completed by Lyft. "
          - name: affiliated_base_number
            data_type: CHARACTER VARYING(256)
            description: "The affiliated TLC license number of the dispatching base"
          - name: filename
            data_type: CHARACTER VARYING(256)

      - name: fhvhv_tripdata
        columns:
          - name: hvfhs_license_num
            data_type: CHARACTER VARYING(256)
            description: "The TLC license number of the HVFHS base or business
                          As of September 2019, the HVFHS licensees are the following:
                          • HV0002: Juno
                          • HV0003: Uber
                          • HV0004: Via
                          • HV0005: Lyft"
          - name: dispatching_base_num
            data_type: CHARACTER VARYING(256)
            description: "The TLC Base License Number of the base that dispatched the trip"
          - name: originating_base_num
            data_type: CHARACTER VARYING(256)
            description: "base number of the base that received the original trip request"
          - name: request_datetime
            data_type: TIMESTAMP
            description: "date/time when passenger requested to be picked up"
          - name: on_scene_datetime
            data_type: TIMESTAMP
            description: "date/time when driver arrived at the pick-up location (Accessible
                          Vehicles-only)"
          - name: pickup_datetime
            data_type: TIMESTAMP
            description: "The date and time of the trip pick-up"
            tests:
              - not_null
              - dbt_expectations.expect_column_to_exist
          - name: dropoff_datetime
            data_type: TIMESTAMP
            description: "The date and time of the trip drop-off"
            tests:
              - not_null
              - dbt_expectations.expect_column_to_exist
          - name: pulocationid
            data_type: BIGINT
            description: "TLC Taxi Zone in which the trip began"
          - name: dolocationid
            data_type: BIGINT
            description: "TLC Taxi Zone in which the trip ended"
          - name: trip_miles
            data_type: DOUBLE
            description: "total miles for passenger trip"
            tests:
              - dbt_expectations.expect_column_values_to_be_between:
                  min_value: 0  # (Optional)
                  max_value: 1350 # (Optional)
          - name: trip_time
            data_type: BIGINT
            description: "total time in seconds for passenger trip"
          - name: base_passenger_fare
            data_type: DOUBLE
            description: "base passenger fare before tolls, tips, taxes, and fees"
          - name: tolls
            data_type: DOUBLE
            description: "total amount of all tolls paid in trip"
          - name: bcf
            data_type: DOUBLE
            description: "total amount collected in trip for Black Car Fund"
          - name: sales_tax
            data_type: DOUBLE
            description: "total amount collected in trip for NYS sales tax"
          - name: congestion_surcharge
            data_type: DOUBLE
            description: "total amount collected in trip for NYS congestion surcharge"
          - name: airport_fee
            data_type: DOUBLE
            descriptioin: "$2.50 for both drop off and pick up at LaGuardia, Newark, and John
                           F. Kennedy airports"
          - name: tips
            data_type: DOUBLE
            description: "total amount of tips received from passenger"
          - name: driver_pay
            data_type: DOUBLE
            description: "total driver pay (not including tolls or tips and net of commission,
                          surcharges, or taxes)"
          - name: shared_request_flag
            data_type: CHARACTER VARYING(256)
            description: "Did the passenger agree to a shared/pooled ride, regardless of
                          whether they were matched? (Y/N)"
            tests:
              - accepted_values:
                  values: ["Y", "N"]
                  config:
                    severity: warn
          - name: shared_match_flag
            data_type: CHARACTER VARYING(256)
            description: "Did the passenger share the vehicle with another passenger who
                          booked separately at any point during the trip? (Y/N)"
            tests:
              - accepted_values:
                  values: ["Y", "N"]
                  config:
                    severity: warn
          - name: access_a_ride_flag
            data_type: CHARACTER VARYING(256)
            description: "Was the trip administered on behalf of the Metropolitan
                          Transportation Authority (MTA)? (Y/N)"
            tests:
              - accepted_values:
                  values: ['Y', 'N']
                  config:
                    severity: warn
          - name: wav_request_flag
            data_type: CHARACTER VARYING(256)
            description: "Did the passenger request a wheelchair-accessible vehicle (WAV)?
                          (Y/N)"
            tests:
              - accepted_values:
                  values: ["Y", "N"]
                  config:
                    severity: warn
          - name: wav_match_flag
            data_type: CHARACTER VARYING(256)
            description: "Did the passenger share the vehicle with another passenger who
                          booked separately at any point during the trip? (Y/N)"
            tests:
              - accepted_values:
                  values: ["Y", "N"]
                  config:
                    severity: warn
          - name: filename
            data_type: CHARACTER VARYING(256)

      - name: green_tripdata
        columns:
          - name: vendorid
            data_type: BIGINT
          - name: lpep_pickup_datetime
            data_type: TIMESTAMP
          - name: lpep_dropoff_datetime
            data_type: TIMESTAMP
          - name: store_and_fwd_flag
            data_type: CHARACTER VARYING(256)
          - name: ratecodeid
            data_type: DOUBLE
          - name: pulocationid
            data_type: BIGINT
          - name: dolocationid
            data_type: BIGINT
          - name: passenger_count
            data_type: DOUBLE
          - name: trip_distance
            data_type: DOUBLE
          - name: fare_amount
            data_type: DOUBLE
          - name: extra
            data_type: DOUBLE
          - name: mta_tax
            data_type: DOUBLE
          - name: tip_amount
            data_type: DOUBLE
          - name: tolls_amount
            data_type: DOUBLE
          - name: ehail_fee
            data_type: INTEGER
          - name: improvement_surcharge
            data_type: DOUBLE
          - name: total_amount
            data_type: DOUBLE
          - name: payment_type
            data_type: DOUBLE
          - name: trip_type
            data_type: DOUBLE
          - name: congestion_surcharge
            data_type: DOUBLE
          - name: filename
            data_type: CHARACTER VARYING(256)

      - name: yellow_tripdata
        columns:
          - name: vendorid
            data_type: BIGINT
          - name: tpep_pickup_datetime
            data_type: TIMESTAMP
          - name: tpep_dropoff_datetime
            data_type: TIMESTAMP
          - name: passenger_count
            data_type: DOUBLE
          - name: trip_distance
            data_type: DOUBLE
          - name: ratecodeid
            data_type: DOUBLE
          - name: store_and_fwd_flag
            data_type: CHARACTER VARYING(256)
          - name: pulocationid
            data_type: BIGINT
          - name: dolocationid
            data_type: BIGINT
          - name: payment_type
            data_type: BIGINT
          - name: fare_amount
            data_type: DOUBLE
          - name: extra
            data_type: DOUBLE
          - name: mta_tax
            data_type: DOUBLE
          - name: tip_amount
            data_type: DOUBLE
          - name: tolls_amount
            data_type: DOUBLE
          - name: improvement_surcharge
            data_type: DOUBLE
          - name: total_amount
            data_type: DOUBLE
          - name: congestion_surcharge
            data_type: DOUBLE
          - name: airport_fee
            data_type: DOUBLE
          - name: filename
            data_type: CHARACTER VARYING(256)
